services:
  lgtm:
    container_name: otel_polyglot_lgtm
    image: grafana/otel-lgtm:latest
    volumes:
      - './prometheus/prometheus.yaml:/otel-lgtm/prometheus.yaml:ro'
      - './otel/collector/config.yaml:/otel-lgtm/otelcol-config.yaml:ro'
      - './certs:/etc/otel/certs:ro'
    restart: always
    environment:
      - ENABLE_LOGS_OTELCOL=true
    ports:
      - "3000:3000"
      - "9000:9000"
