services:
  py-fastapi:
    container_name: otel_polyglot_py_fastapi
    build:
      context: services/py-fastapi
      target: dev
    volumes:
      - './services/py-fastapi:/usr/code'
      - './certs:/etc/otel/certs:ro'
      - './certs/ca.crt:/usr/local/share/ca-certificates/otel-ca.crt:ro'
    working_dir: '/usr/code'
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://lgtm:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=false
      - OTEL_EXPORTER_OTLP_CERTIFICATE=/etc/otel/certs/ca.crt
      - OTEL_LOGS_EXPORTER=otlp
    env_file:
      - .env
    entrypoint: [ '/bin/sh', '-c', 'sleep infinity' ]
    restart: always
    depends_on:
      lgtm:
        condition: service_started
